apiVersion: apps/v1
kind: Deployment
metadata:
  name: redis
  labels:
    app: redis
spec:
  replicas: 1
  selector:
    matchLabels:
      app: redis
      tier: redis
  template:
    metadata:
      labels:
        app: redis
        tier: redis
    spec:
      containers:
        - name: redis
          image: redis:latest
          livenessProbe:
            tcpSocket:
              port: 6379
          ports:
            - name: redis
              containerPort: 6379
---
apiVersion: v1
kind: Service
metadata:
  name: redis
  labels:
    app: redis
spec:
  selector:
    app: redis
    tier: redis
  clusterIP: None
  ports:
    - port: 6379
      targetPort: 6379
      name: redis