scrape_configs:
  - job_name: 'AuthServiceMetrics'
    metrics_path: '/ebanking/actuator/prometheus'
    scrape_interval: 3s
    static_configs:
      - targets: [ 'host.docker.internal:8081' ]
        labels:
          application: 'Ebanking Auth Application'
  - job_name: 'TransactionServiceMetrics'
    metrics_path: '/ebanking/actuator/prometheus'
    scrape_interval: 3s
    static_configs:
      - targets: [ 'host.docker.internal:8082' ]
        labels:
          application: 'Ebanking Transaction Application'